package org.mountcloud.springmvc.framework.mysql.mapper;

import org.apache.ibatis.annotations.Param;
import org.mountcloud.springmvc.framework.mysql.entity.BaseEntity;
import org.mountcloud.springmvc.framework.mysql.entity.BaseExample;

import java.util.List;

/**
 * 
* @Title: BaseMapper.java 
* @Package com.coconet.common.mapper 
* @Description: TODO
* @author zhanghaishan
* @date 2017年8月22日 下午5:00:39 
* @version V1.0
 */
public interface BaseMapper {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseExample> Long countByExample(D example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseExample> int deleteByExample(D example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseEntity> int insert(D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseEntity> int insertSelective(D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseEntity,E extends BaseExample> List<D> selectByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseEntity> D selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseEntity,E extends BaseExample> int updateByExampleSelective(@Param("record") D record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseEntity,E extends BaseExample> int updateByExample(@Param("record") D record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseEntity> int updateByPrimaryKeySelective(D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseEntity> int updateByPrimaryKey(D record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 
     *
     * @mbggenerated Tue Aug 22 15:20:02 CST 2017
     */
    public <D extends BaseExample> List selectCustomByExample(D example);
}
